### ISSUE TITLE
what is the release date of ms-loss?

### ISSUE THREAD

**Issue by LeeRock** [MalongTech/research-ms-loss#1]
dear @mscottml ，i have just read the paper "Multi-Similarity Loss with General Pair Weighting
for Deep Metric Learning" .It's a great job I have ever seen in metrics learning. 
Would you please release the code and show more details ?Thank you very much.

**Comment by mscottml** [comment]
Thank you! We are working on releasing more information, but we don’t have an ETA right now.

On Jun 23, 2019, at 10:17 PM, leerock <notifications@github.com<mailto:notifications@github.com>> wrote:


dear @mscottml<https://github.com/mscottml> ，i have just read the paper "Multi-Similarity Loss with General Pair Weighting
for Deep Metric Learning" .It's a great job I have ever seen in metrics learning.
Would you please release the code an show more details ?Thank you very much.

**Comment by autocyz** [comment]
Paper insight is so cool, especially general pair weighting. It help us to understand metric learning loss insight.   Looking forward to release code, especially pair mining code.

**Comment by Miles-Ma** [comment]
Read your paper. Cool. Looking forward to your code.

**Comment by mscottml** [comment]
Thank you all for your interest in our research - w will release it as soon as we can. Appreciate your patience. Please turn on the 'Watch' feature of Github on this repository to get updated immediately upon release.
