### ISSUE TITLE
Loss is not stable and sometimes Nan

### ISSUE THREAD

**Issue by autocyz** [MalongTech/research-ms-loss#12]
I use resnet50 + MS loss to train my own dataset,  but sometimes loss will be Nan, it seems that the loss is not very stable

**Comment by bnu-wangxun** [comment]
Maybe the reason is the learn rate you use is two large, and the the exp part of the loss go Nan.

**Comment by chammika-become** [comment]
I managed to get resent50 working. Check this out
https://github.com/chammika-become/research-ms-loss/commit/d0c49eb

You need to download the official weights to `~/.torch/models/resnet50-19c8e357.pth`

**Comment by mscottml** [comment]
@autocyz , the comments in this thread should answer your issue.
