### ISSUE TITLE
Cars-196 experiments settings

### ISSUE THREAD

**Issue by visenzeadam** [MalongTech/research-ms-loss#6]
I cannot see any experiments setting for Cars-196, can you show the yaml config also?

When I use the CUB-200's yaml config to train the Cars-196(followed the paper's training split rule, 98 classes), but only got best R@1=78.4%(the embedding size is 512), much lower than 84.1% in your paper.

Thanks,
Adam

**Comment by lenscloth** [comment]
@visenzeadam 
Did you reproduce the result on Cars-196?

**Comment by geonm** [comment]
@lenscloth 

Hi.

You can easily reproduce the results on CARS196.

Use the large batch size more than 450.

**Comment by lenscloth** [comment]
@geonm Thanks!

**Comment by wanghao14** [comment]
@geonm Hi, how could you use such big batch size? Do you use distributed training?
