### ISSUE TITLE
train.txt and test.txt

### ISSUE THREAD

**Issue by lenscloth** [MalongTech/research-ms-loss#7]
First of all, thanks you for a great work!

Can you upload ```train.txt``` and ```test.txt``` files for training CUB-200-2011 dataset?

**Comment by mscottml** [comment]
Thank you. Please follow the instructions on the homepage of this repo to download the dataset. In the folder names after download, there is a category number in this format [cat-number].[cat-name]. It is straightforward to create the related training files from this structure.

**Comment by Paul0M** [comment]
```python
# /disk2/Paul/CUB200/gen_train_test.py
import os

datadir = r'/disk2/Paul/CUB200/images'
cats = os.listdir(datadir)

N = len(cats)//2 # for CUB200

with open('train.txt', 'w') as fin:
    for i,cat in enumerate(cats[:N]):
        for filename in os.listdir(os.path.join(datadir, cat)):
            if filename.startwith(r'._'):continue
            f_str = '/'.join(['images', cat, filename]) + ',' + str(i) + '\n'
            print(f_str)
            fin.write(f_str) 

with open('test.txt', 'w') as fin:
    for i,cat in enumerate(cats[N:]):
        for filename in os.listdir(os.path.join(datadir, cat)):
            if filename.startwith(r'._'):continue
            f_str = '/'.join(['images', cat, filename]) + ',' + str(i) + '\n'
            print(f_str)
            fin.write(f_str)             
```

**Comment by wangaxe** [comment]
> ```python
> # /disk2/Paul/CUB200/gen_train_test.py
> import os
> 
> datadir = r'/disk2/Paul/CUB200/images'
> cats = os.listdir(datadir)
> 
> N = len(cats)//2 # for CUB200
> 
> with open('train.txt', 'w') as fin:
>     for i,cat in enumerate(cats[:N]):
>         for filename in os.listdir(os.path.join(datadir, cat)):
>             if filename.startwith(r'._'):continue
>             f_str = '/'.join(['images', cat, filename]) + ',' + str(i) + '\n'
>             print(f_str)
>             fin.write(f_str) 
> 
> with open('test.txt', 'w') as fin:
>     for i,cat in enumerate(cats[N:]):
>         for filename in os.listdir(os.path.join(datadir, cat)):
>             if filename.startwith(r'._'):continue
>             f_str = '/'.join(['images', cat, filename]) + ',' + str(i) + '\n'
>             print(f_str)
>             fin.write(f_str)             
> ```

Thank you for this script! Find a little typo, startwith should be startswith.
